config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  root 'welcome#index'
  get     'contact'   => 'welcome#contact'
  get     'news'      => 'welcome#news'
  get     'about'      => 'welcome#about'

  resources :posts
  resources :terms do
    get :autocomplete_term_phrase, :on => :collection
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  def email_required?
    false
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 6
  validates :title, presence: true, length: { minimum: 5, maximum: 20 }
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/term.rb
class Term < ActiveRecord::Base
  self.per_page = 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :password)}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :destroy, :update]
before_filter :authenticate_admin, only: [:edit, :destroy, :update, :new, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @posts = Post.all.order('created_at DESC').page(params[:page])
  end

  def destroy
    @post.delete
    redirect_to posts_path
    flash[:notice] = "News successfuly deleted."
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to posts_path
      flash[:success] = "News successfuly updated."
    else
      render 'edit'
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

    def find_post
      @post = Post.find(params[:id])
    end

    def authenticate_admin
      unless admin_signed_in?
        redirect_to root_path
        flash[:danger] = "Tylko administrator ma tu dostęp."
      end
    end

end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
autocomplete :term, :phrase

  def new
    @term = Term.new
  end

  def create
    @term = Term.new term_params
    if @term.save
      redirect_to terms_path
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
  end

  def index
    if params[:search]
      unless /^ +/.match(params[:search]) || /%+/.match(params[:search])
        @terms = Term.where(['phrase LIKE :search OR explanation LIKE :search', search: "%#{params[:search]}%"]).order("phrase ASC").page(params[:page])
        if params[:search].length == 1 # Check if searched by clicking on Alphabet letter on index page.
          #@terms = Term.where(['phrase LIKE :search', search: "%#{params[:search]}%"]).order("phrase ASC")
          @terms = Term.where(['substr(phrase, 1, 1) LIKE :search', search: "%#{params[:search]}%"]).order("phrase ASC").page(params[:page])
        end
        if @terms.count == 0
          flash[:notice] = "No terms found."
          redirect_to :back
        end
      else
        flash[:notice] = "Błędny format."
        redirect_to :back
      end
    else
      @terms = Term.all.order("phrase ASC").page(params[:page])
    end
  end

  def show
    @term = Term.find(params[:id])
  end

  private

    def term_params
      params.require(:term).permit(:phrase, :explanation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def contact
  end

  def about
  end

  def news
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="foot_wrap">
    <div class="foot_pict"></div>
      <div class="foot_text_wrap">
        <div class="foot_text">
          Copyright &copy; Koło Naukowe Ubezpieczeń Risk Management 2016
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">

    <div class="logo">
        <div class="logo_cont">

            <%= link_to root_path do %>
                <div class="logo_risk"></div>
            <% end %>
            <div style="width: 50px; float: left; height: 100%;"></div>
            <%= link_to "http://uek.krakow.pl", target: "_blank" do %>
                <div class="logo_uek"></div>
            <% end %>

        </div>
    </div>

    <div class="menu">
        <div class="menu_cont">
            <ul id="men">
                <li><%= link_to "O NAS", about_path %></li>
                <li><%= link_to "AKTUALNOŚCI", posts_path %></a></li>
                <li><%= link_to "LEKSYKON POJĘĆ UBEZPIECZENIOWYCH", terms_path %></li>
                <li><%= link_to "KONTAKT", contact_path %></li>
                <% if admin_signed_in? %>
                    <li><%= link_to "DODAJ NEWS'A", new_post_path %></li>
                    <li><%= link_to "DODAJ TERMIN", new_term_path %></li>
                    <li><%= link_to "WYLOGUJ", destroy_admin_session_path, method: :delete %></li>
                <% end %>
            </ul>
        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uekleksykon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :application, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <div class="content_other">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash #{key}" %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<h1><%= post.title %></h1>
<%= truncate(post.content, length: 200) %>

app/views/posts/edit.html.erb
<div class="content_other">
  <div class="new_post">
    <%= form_for @post do |f| %>

      <div class="field">
      <%= f.label :title, "Tytuł" %><br>
      <%= f.text_field :title %>
      </div>

      <div class="field">
      <%= f.label :content, "Zawartość" %><br>
      <%= f.text_area :content %>
      </div>

      <%= f.submit "Edytuj" %>

    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="content_other news">
  <div class="head_con">
     Aktualności
  </div>
    <div class="con_con">
    <% @posts.each do |post| %>
      <%= link_to post do %>
        <div class="wrapbox">

          <div class="box">
            <div class="box_cont">
                <div class="b_date"><%= post.created_at.strftime("%d-%m-%Y") %></div>
              <div class="b_info">

              <%= render post %>

              </div>
            </div>
          </div>

        </div>
      <% end %>
    <% end %>
    </div>
    <%= will_paginate @posts, class: "pagination bottom", :previous_label => '←', :next_label => '→' %>
</div>
<div style="clear: both"></div>

app/views/posts/new.html.erb
<div class="content_other">
  <div class="new_post">

    <%= form_for @post do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

      <div class="field">
        <%= f.label :title, "Tytuł" %><br>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :content, "Zawartość" %><br>
        <%= f.text_area :content %>
      </div>

      <%= f.submit "Dodaj" %>

    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<%= @post.title %><br>
<%= @post.content %>
<% if admin_signed_in? %>
  <div class="admin_post">
    <span class="edit"><%= link_to "Edit", edit_post_path(@post) %></span>
    <span class="delete"><%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %></span>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/terms/_term.html.erb
<%= term.phrase %> -
<%= term.explanation %>

app/views/terms/index.html.erb
<div class="terms">
    <div class="content_other">
              <div class="head_con">
                  Leksykon pojeć ubezpieczeniowych
              </div>
              <div class="contact">
                  <div class="search">
                    <%= form_tag terms_path, method: 'get' do%>
                      <%= autocomplete_field_tag :search, params[:search], autocomplete_term_phrase_terms_path %>
                      <%= submit_tag "Search", name: nil %>
                      <% if params[:search] %>
                        <%= link_to "cancel", terms_path %>
                      <% end %>
                    <% end %>
                 </div>
                <ul class="letters">
                     <li><%= link_to "A",  controller: "terms", method: "search", search: "a" %></li>
                     <li><%= link_to "B", controller: "terms", method: "index", search: "b" %></li>
                     <li><%= link_to "C", controller: "terms", method: "index", search: "c" %></li>
                     <li><%= link_to "D", controller: "terms", method: "index", search: "d" %></li>
                     <li><%= link_to "E", controller: "terms", method: "index", search: "e" %></li>
                     <li><%= link_to "F", controller: "terms", method: "index", search: "f" %></li>
                     <li><%= link_to "G", controller: "terms", method: "index", search: "g" %></li>
                     <li><%= link_to "H", controller: "terms", method: "index", search: "h" %></li>
                     <li><%= link_to "I", controller: "terms", method: "index", search: "i" %></li>
                     <li><%= link_to "J", controller: "terms", method: "index", search: "j" %></li>
                     <li><%= link_to "K", controller: "terms", method: "index", search: "k" %></li>
                     <li><%= link_to "L", controller: "terms", method: "index", search: "l" %></li>
                     <li><%= link_to "M", controller: "terms", method: "index", search: "m" %></li>
                     <li><%= link_to "N", controller: "terms", method: "index", search: "n" %></li>
                     <li><%= link_to "O", controller: "terms", method: "index", search: "o" %></li>
                     <li><%= link_to "P", controller: "terms", method: "index", search: "p" %></li>
                     <li><%= link_to "R", controller: "terms", method: "index", search: "r" %></li>
                     <li><%= link_to "S", controller: "terms", method: "index", search: "s" %></li>
                     <li><%= link_to "T", controller: "terms", method: "index", search: "t" %></li>
                     <li><%= link_to "U", controller: "terms", method: "index", search: "u" %></li>
                     <li><%= link_to "Y", controller: "terms", method: "index", search: "y" %></li>
                     <li><%= link_to "Z", controller: "terms", method: "index", search: "z" %></li>
                 </ul><hr>
                  <ul class="words">
                  <% @terms.each do |term| %>
                    <%= link_to term do %>
                    <li><%= term.phrase %></li>
                    <% end %>
                  <% end %>
                  </ul>
                  <%= will_paginate @terms, class: "pagination bottom", :previous_label => '←', :next_label => '→' %>
             </div>
              </div>
</div>

app/views/terms/new.html.erb
<%= form_for @term do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :phrase, "Termin" %><br>
    <%= f.text_field :phrase %>
  </div>

  <div class="field">
    <%= f.label :explanation, "Znaczenie" %><br>
    <%= f.text_area :explanation %>
  </div>

  <%= f.submit "Dodaj termin" %>

<% end %>

app/views/terms/show.html.erb
<%= render @term %>

app/views/welcome/about.html.erb
<div class="content_other">
            <div class="head_con">
                O nas
            </div>
            <div class="about">

                 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lorem lacus, commodo eu augue sit amet, feugiat mollis elit. Sed auctor velit convallis, mollis sem a, accumsan risus. Maecenas hendrerit non elit sed lobortis. In luctus venenatis sem eu lacinia. Fusce id leo ante. Donec fringilla bibendum nisi vitae facilisis. Vivamus iaculis, lorem non dignissim malesuada, risus tellus lacinia tortor, quis commodo mi sem et elit. Mauris scelerisque lobortis est, ut ultrices orci dapibus sit amet. In ac gravida nulla. Morbi non enim eget orci sagittis pellentesque.

Mauris imperdiet imperdiet justo at maximus. Etiam tempus porta eros, ut pellentesque tortor lacinia ut. In congue felis vitae mi viverra vehicula. Duis tincidunt maximus sodales. Duis eu sem semper, facilisis metus auctor, ornare libero. Vivamus rhoncus elementum neque nec ornare. Sed nec fermentum dui. Morbi vitae diam ac nibh mollis congue ut sit amet ante.

Fusce tempus ac tortor eu molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vitae magna vel lacus facilisis fringilla. Donec eget nisl sit amet risus dictum accumsan. Vestibulum mattis tellus magna. Vestibulum ac scelerisque nisl, et varius velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ac rhoncus lorem. Nullam porttitor quam in tellus sollicitudin dignissim. Curabitur sed efficitur enim. Mauris non felis odio. Nullam tincidunt eget risus dignissim fringilla. Phasellus volutpat vel felis nec mollis. Maecenas varius scelerisque nunc, nec molestie diam faucibus eget. Vivamus bibendum et turpis in ornare. Phasellus ac accumsan lacus, vitae feugiat sapien.  Nullam ut ligula cursus, finibus lectus vel, fringilla quam. Nunc auctor ligula vel lacus dictum interdum. In vitae pharetra dui. Pellentesque at placerat urna. Phasellus convallis tempus lorem a tempus. Etiam nec lorem elementum, pellentesque ipsum eget, suscipit felis. Mauris quis venenatis purus. Integer et luctus libero, at finibus eros. Nam eu tristique mi, dignissim convallis lectus. Cras non eros sed lacus lacinia facilisis. Morbi commodo rutrum porttitor.

Vestibulum nisi diam, dapibus vitae nibh id, pulvinar suscipit neque. Proin id felis volutpat ipsum volutpat auctor. Maecenas nisl mi, rhoncus a dictum quis, tristique in erat. Pellentesque nec elit neque. Nunc ipsum massa, viverra vel tristique nec, imperdiet sed libero. Vivamus et auctor velit, eu convallis ligula. Duis sem urna, euismod at tellus eget, tempus lobortis ante. Aenean velit erat, accumsan non rhoncus non, dapibus vitae neque. Cras euismod laoreet orci. Vivamus commodo, justo quis condimentum vehicula, erat sapien interdum eros, ac dignissim purus mauris vitae magna. Sed lectus dolor, faucibus vel purus ut, egestas mollis nibh. Aliquam eu posuere nulla, eu tristique enim. Nam placerat eros nibh, nec tristique ante sagittis vel. Donec in posuere felis. Nullam nec aliquam dolor. Suspendisse cursus urna vel arcu ullamcorper tincidunt.

            </div>
            </div>

app/views/welcome/contact.html.erb
<div class="content_other">
  <div class="head_con">
    Kontakt
  </div>
  <div class="contact">

    <b>Uniwersytet Ekonomiczny w Krakowie</b><br> ul. Rakowicka 27,<br> 31-510 Kraków<br><br>
    pawilon F, VI p.<br>Sekretariat (p.602) (Katedra Ubezpieczeń)<br>tel: (0-12) 293-50-81<br><br>
    e-mail: <a href="mailto:kuinfo@uek.krakow.pl" title="Wyślij wiadomość">kuinfo@uek.krakow.pl</a><br>e-mail: <a href="mailto:knukrakow@gmail.com" title="Wyślij wiadomość">knukrakow@gmail.com</a>
    </div>
</div>

app/views/welcome/index.html.erb
HELLO

app/views/welcome/news.html.erb
AKTUALNOSCI